version: "3.9"
services:
  db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./share/init.sql:/docker-entrypoint-initdb.d/init.sql
      - .datastore/postgres:/var/lib/postgresql/data
    networks:
      - coins-network
  api:
    build:
      context: .
      dockerfile: deployment/Dockerfile
    command: dev
    environment:
      PORT: 8000
      DATABASE_URL: "postgresql+asyncpg://coins:password@postgres:5432/coins"
      HOST: 0.0.0.0
    volumes:
      - .:/app
    networks:
      - coins-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./scripts/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./scripts/nginx/sites-enabled/:/etc/nginx/sites-enabled/:ro
      - ./scripts/nginx/common/:/etc/nginx/common/:ro
      - .datastore/nginx/certs/:/etc/nginx/ssl/:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - coins-network

networks:
  coins-network:
    name: coins-network
    external: true