---
name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # check-out repo
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'poetry'

      - name: Install poetry dependencies
        run: poetry install --no-interaction

      - name: Pytest
        env:
          SECRET_KEY: "abc"
          DATABASE_URL: "sqlite://test.db"
        run: |
          poetry run black --check .
          poetry run flake8 .
          poetry run isort --check-only .
          poetry run python manage.py test


  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install poetry dependencies
        run: pip install python-semantic-release

      - name: Python Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          # Set git details
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@devsoft.pl"

          # run semantic-release
          semantic-release version
          semantic-release publish